apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busy-dep-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage-retain
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-dep
  namespace: default
  labels:
    app: busy-dep-app
  # annotations:
  #   blueprint.kubestash.com/name: deploy-blueprint
  #   blueprint.kubestash.com/namespace: demo
  #   variables.kubestash.com/targetName: busy-dep-pvc
  #   variables.kubestash.com/namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busy-dep-app
  template:
    metadata:
      labels:
        app: busy-dep-app
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      restartPolicy: Always
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: busy-dep-pvc
