apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-backup
spec:
  image: ishtiaq99/workload:6f71e6e_linux_amd64
  args:
  - backup
  - --scratchDir=/tmp
  - --namespace=${namespace:=default}
  - --backupSession=${backupSession:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-restore
spec:
  image: ishtiaq99/workload:6f71e6e_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoreSession=${restoreSession:=}
  - --snapshotName=${snapshotName:=}

---

apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: default
spec:
  storage:
    provider: s3
    s3:
      endpoint: us-east-1.linodeobjects.com
      bucket: kubestash
      region: us-east-1
      prefix: demo
      secret: s3-secret 
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true # Use this BackupStorage as the default
  deletionPolicy: WipeOut # One of: WipeOut, Delete

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: workload-addon
  namespace: default
spec:
  backupTasks:
    - name: backup-workload
      function: workload-backup
      driver: Restic #Restic, WalG
      executor: Job #Job, Sidecar, EphemeralContainer, MultiLevelJob
  restoreTasks:
    - name: restore-workload
      function: workload-restore
      driver: Restic
      executor: Job

---

apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: demo-retention
  namespace: default
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 5
  failedSnapshots:
    last: 2
  usagePolicy:
    allowedNamespaces:
      from: All